### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by andrew-davis** [willswire/unifi-cloudflare-ddns#21]
I followed the steps in the readme to configure Cloudflare for my Dream Machine. When I go to my worker url, I see 'not found'. Is that the expected behavior?

**Comment by Cohors1316** [comment]
pretty much. your worker is expecting additional information to be sent with the url, and since that information is missing it fails to the `not found` response. If I'm reading it right you might not have added the `/update` at the end of your worker, which would have failed every case in the switch.

**Comment by andrew-davis** [comment]
Thank you for responding! I'm new to this, and trying to learn.

I did append 'update' to the string I entered into the server field of the dyndns setup on my UDM. Following the instructions, it looks like this:

`xxxx.xxxx.workers.dev/update?ip=%i&hostname=%h`

**Comment by willswire** [comment]
@andrew-davis, the behavior you're encountering when visiting the worker url in your browser, is expected as @Cohors1316 mentioned.  the worker does not serve website content like a traditional web server, it is only listening for a HTTP POST from your UniFi device.
